#!/usr/bin/env sh
# PRAHARI-SIM release check (1.0): re-verifies that this checkout still works exactly as released.
#   scripts/check_all.sh           # tests, type check, build, doc links, and every recording regenerated byte for byte
#   scripts/check_all.sh --quick   # the same without regenerating recordings (about 3 minutes)
#   JOBS=8 scripts/check_all.sh    # recordings regenerated 8 at a time (default 4)
# It changes nothing in the repository: regenerated recordings go to a temporary folder and are compared with the
# committed files. Exit status 0 means every check passed.
set -eu
cd "$(dirname "$0")/.."
JOBS="${JOBS:-4}"
fail=0
step() { printf '\n== %s\n' "$1"; }
bad() { echo "FAIL: $1"; fail=1; }

step "engine tests (pytest)"
python3 -m pytest engine/tests -q -W error::RuntimeWarning || bad "engine tests"

step "dashboard: type check, unit tests, build"
( cd dashboard && npx tsc --noEmit -p . && npx vitest run && npm run build ) || bad "dashboard"

step "documentation links"
python3 - <<'EOF' || bad "documentation links"
import pathlib, re, sys
files = list(pathlib.Path("docs").rglob("*.md")) + [pathlib.Path(p) for p in
         ("README.md", "PROGRESS.md", "DECISIONS.md", "KNOWN_ISSUES.md", "CLAUDE.md", "DEMO_CHECKLIST.md")]
broken = [(f, m.group(1)) for f in files for m in re.finditer(r"\]\(([^)#\s]+)(#[^)]*)?\)", f.read_text("utf-8"))
          if not m.group(1).startswith(("http", "mailto")) and not (f.parent / m.group(1)).exists()]
for f, t in broken:
    print(f"broken link in {f}: {t}")
print(f"{len(files)} files, {len(broken)} broken links")
sys.exit(1 if broken else 0)
EOF

if [ "${1:-}" != "--quick" ]; then
  step "recordings: regenerate every scenario and compare bytes ($JOBS at a time; about 10–15 minutes)"
  tmp="$(mktemp -d)"
  ls configs/scenarios/*.yaml | xargs -P "$JOBS" -I{} sh -c \
    'n=$(basename {} .yaml); prahari run --config {} --out "$0/$n.prs.jsonl.gz" >/dev/null 2>&1 || echo "run failed: $n"' "$tmp"
  for f in recordings/*.prs.jsonl.gz; do
    n="$(basename "$f")"
    if cmp -s "$f" "$tmp/$n"; then echo "identical  $n"; else bad "recording differs: $n"; fi
  done
  rm -rf "$tmp"
fi

echo
if [ "$fail" -eq 0 ]; then echo "ALL CHECKS PASSED"; else echo "SOME CHECKS FAILED"; fi
exit "$fail"
